### PR TITLE
Introduce library to host common code shared by FroniusMonitor and FroniusPhone

### PR DESCRIPTION
**Pull request by kaheimri**
…utomationSystem

These are really tied to the application that is build on top of the Fronius library, nothing that can be reused per se by a different home automation system or a different setup of devices.

### CODE REVIEW

**Comment by kaheimri** [comment]
This commit is just a proposal, no need to accept it cause it's your project and application. That's also the reason why it's marked as WIP. I just created the pull  request to maybe start the discussion about keeping your nicely crafted library separated from application logic. Also, since I did not dig deep enough into the code yet, I might have broken some dependencies on the property notifications or chosen the wrong spot for the moved code.

**Comment by christoh** [comment]
Yes, good approach. However, I am also thinking of more refactorings.

- Currently I quickly hacked in a 2nd inverter when I got one for my house. This should actually be a list of inverters.
- Now there is Gen24Sensors/Gen24Sensors2, Gen24Config/Gen24Config2, etc. This should be IList<SomeUnifiedGen24Class>

**Comment by kaheimri** [comment]
I fully agree, I've seen that too. Currently preparing a follow-up that refactors the the ToshibaHvacService to not entirely or not at all depend on SettingsBase and provide an interface modeled more like the other services. I would also propose that some functionality in SettingsBase gets moved into the application, like the FroniusConnection* properties, Show/Have properties and so on. I will push that patch probably tomorrow.

**Comment by HugoX104447** [comment]
I've done all of the necessary refactoring to move application specific code into either FroniusMonitor or FroniusPhone app. Looking at this, I think instead of having the same code duplicated in both apps, it might make more sense to have a small shared library for both. If you are fine with moving the code out of the core lib, I will continue to merge it into this new shared lib. What do you think, does it makes sense to move along?

**Comment by christoh** [comment]
Absolutely agree. This approach also gives the opportunity to quickly move code between the core lib and the new shared lib in the unlikely case something had been placed where it shouldn't be.

**Comment by HugoX104447** [comment]
I have finalized the changes, resulting in the two commits in this pull-request. Not sure how I can edit the title though...

**Comment by christoh** [comment]
image

**Comment by HugoX104447** [comment]
Strange, I do not have the 'Edit' button.
image

**Comment by christoh** [comment]
I'll check permissions

**Pull request merged**
